"""
Cerevox SDK Core Components

This module contains the core infrastructure components including base clients,
exceptions, and data models.
"""

from .async_base_client import AsyncBaseClient
from .base_client import BaseClient
from .exceptions import (
    InsufficientPermissionsError,
    LexaAuthError,
    LexaError,
    LexaJobFailedError,
    LexaRateLimitError,
    LexaTimeoutError,
    LexaValidationError,
    create_error_from_response,
)
from .models import (
    VALID_MODES,
    AccountInfo,
    AccountPlan,
    AskItem,
    AsksListResponse,
    AskSubmitRequest,
    BucketListResponse,
    ChatCreate,
    ChatCreatedResponse,
    ChatItem,
    ChatsListResponse,
    CreatedResponse,
    DeletedResponse,
    DriveListResponse,
    FileInfo,
    FileItem,
    FilesListResponse,
    FileUploadResponse,
    FolderCreate,
    FolderCreatedResponse,
    FolderItem,
    FolderListResponse,
    FoldersListResponse,
    IngestionResult,
    JobResponse,
    JobStatus,
    MessageResponse,
    ProcessingMode,
    TokenRefreshRequest,
    TokenResponse,
    UpdatedResponse,
    UsageMetrics,
    User,
    UserCreate,
    UserDelete,
    UserUpdate,
)

__all__ = [
    # Base clients
    "BaseClient",
    "AsyncBaseClient",
    # Exceptions
    "LexaError",
    "LexaAuthError",
    "LexaRateLimitError",
    "LexaTimeoutError",
    "LexaJobFailedError",
    "LexaValidationError",
    "InsufficientPermissionsError",
    "create_error_from_response",
    # Models - Account related
    "AccountInfo",
    "AccountPlan",
    "CreatedResponse",
    "DeletedResponse",
    "MessageResponse",
    "TokenRefreshRequest",
    "TokenResponse",
    "UpdatedResponse",
    "UsageMetrics",
    "User",
    "UserCreate",
    "UserDelete",
    "UserUpdate",
    # Models - Hippo (RAG) related
    "AskItem",
    "AsksListResponse",
    "AskSubmitRequest",
    "ChatCreate",
    "ChatCreatedResponse",
    "ChatItem",
    "ChatsListResponse",
    "FileItem",
    "FilesListResponse",
    "FileUploadResponse",
    "FolderCreate",
    "FolderCreatedResponse",
    "FolderItem",
    "FoldersListResponse",
    # Models - Lexa (Document Processing) related
    "VALID_MODES",
    "BucketListResponse",
    "DriveListResponse",
    "FileInfo",
    "FolderListResponse",
    "IngestionResult",
    "JobResponse",
    "JobStatus",
    "ProcessingMode",
]
