name: Bug Report
description: File a bug report to help us improve
title: "[BUG] "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your bug report
      options:
        - label: I have searched existing issues to ensure this bug has not already been reported
          required: true
        - label: I have read the [Contributing Guidelines](../CONTRIBUTING.md)
          required: true
        - label: I have read the [Code of Conduct](../CODE_OF_CONDUCT.md)
          required: true

  - type: textarea
    id: summary
    attributes:
      label: Bug Summary
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug in a few sentences
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps to reproduce the behavior
      placeholder: |
        1. Import cerevox with '...'
        2. Call function '...' with parameters '...'
        3. See error
      value: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened? Include error messages if any.
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Minimal Reproducible Example
      description: Please provide a minimal code example that reproduces the issue
      placeholder: |
        ```python
        import cerevox
        
        # Your minimal reproducible code here
        ```
      render: python
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: Please provide information about your environment
      placeholder: |
        - OS: [e.g. Ubuntu 20.04, macOS 12.0, Windows 10]
        - Python version: [e.g. 3.9.7]
        - cerevox version: [e.g. 1.0.0]
        - Installation method: [e.g. pip, conda, from source]
      value: |
        - OS: 
        - Python version: 
        - cerevox version: 
        - Installation method: 
    validations:
      required: true

  - type: textarea
    id: traceback
    attributes:
      label: Full Traceback
      description: If applicable, please provide the full error traceback
      placeholder: Paste the complete error traceback here
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Screenshots, logs, related issues, etc.
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute a fix for this bug?
      options:
        - label: I would be willing to submit a PR to fix this bug
          required: false 