name: Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: terms
    attributes:
      label: Prerequisites
      description: Please confirm the following before submitting your feature request
      options:
        - label: I have searched existing issues to ensure this feature has not already been requested
          required: true
        - label: I have read the [Contributing Guidelines](../CONTRIBUTING.md)
          required: true
        - label: I have checked the [roadmap and project goals](../README.md) to ensure this aligns with the project
          required: true

  - type: dropdown
    id: feature_type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New API functionality
        - Performance improvement
        - Developer experience improvement
        - Documentation enhancement
        - Testing improvement
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like to see
      placeholder: Briefly describe the feature in 1-2 sentences
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What is the motivation for this request?
      placeholder: |
        Describe the problem you're trying to solve or the limitation you've encountered.
        Is your feature request related to a problem? Please describe.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: |
        A clear and concise description of what you want to happen.
        How should this feature work? What should the API look like?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: |
        What other approaches have you considered?
        Are there existing workarounds or third-party solutions?
    validations:
      required: false

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: If applicable, provide an example of how this feature would be used
      placeholder: |
        ```python
        import cerevox
        
        # Example of how the new feature would be used
        result = cerevox.new_feature(parameter="value")
        ```
      render: python
    validations:
      required: false

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What are the benefits of implementing this feature?
      placeholder: |
        - Improved performance
        - Better developer experience
        - Solves common use case
        - etc.
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my work
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or links about the feature request
      placeholder: Links to similar implementations, mockups, related issues, etc.
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to implementing this feature?
      options:
        - label: I would be willing to submit a PR to implement this feature
          required: false
        - label: I would be willing to help with testing this feature
          required: false
        - label: I would be willing to help with documentation for this feature
          required: false 